# Your name and what you do
name: Hong Kyu, Lee
bio: Software Engineer

description: Hongkyu Lee's personal website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://redKyu.github.io/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
# twitter: mytwitter
linkedin: https://www.linkedin.com/in/hongkyu-lee-9b28ab20a/
# github: mygithub
email: hongkyu.lee@IEEE.org
# cv: cv
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# do you want to display an about section? true or false
about: true


educations: True
education-list:
    KSU:
        school: Kennesaw State University
        degree: Master of Science in Computer Science
        gpa: 'GPA: 4.0/4.0'
    HYU:
        school: Hanyang University ERICA
        degree: Bachelor of Science in Electrical Engineering
        gpa: 'GPA: 3.81/4.0'

# publications
publications: true

publication-list:
    ICC:
        title: On Defensive Neural Network Against Federated Learning
        authors:  Hongkyu Lee, Jeehyeong Kim, Rasheed Hussain, Sunghyun Cho, and Junggab Son
        conference: 'IEEE International Conference on Communications (ICC) Communication and Information Systems Security Symposium (CISS), pages 1-6, June, 2021'
        url: https://ieeexplore.ieee.org/abstract/document/9500936

    Elsevier:
        title: 'Digestive Neural Networks: A Novel Defense Strategy Against Inference Attacks in Federated Learning'
        authors:  Hongkyu Lee, Jeehyeong Kim, Seyoung Ahn, Rasheed Hussain, Sunghyun Cho, and Junggab Son
        conference: Computers & Security, 109 (), pages , October, 2021.
        url: https://www.sciencedirect.com/science/article/pii/S0167404821002029?via%3Dihub

    Luke:
        title:  Efficient yet Robust Privacy Preservation for MPEG-DASH Based Video Streaming
        authors: Luke Cranfil, Jeehyeong Kim, Hongkyu Lee, Victor Youdom Kemmoe, Sunghyun Cho, and Junggab Son
        conference: Security and Communication Networks, (), pages , , 2021
        url: https://www.hindawi.com/journals/scn/2021/4702469/

awardgrants: true

awardgrant-list:
    ICC:
        title: ICC 2021 Student Grant
        fundsource: 'US National Science Foundation (NSF)'


       

# do you want to display a projects section? true or false
projects: false

# add your projects here
project-list:
    example:
        name: title
        description: description
        url: https://github.com/jibolash/Eve


# do you want to display a skills section? true or false
skills: false

# add your skills here
skills-list:
    - HTML, Jade
    - CSS (Stylus, Sass, Less)
    - Javascript, NodeJS
    - AngularJS, ReactJS
    - Java, Android
    - Python
    - MySQL - MongoDB    
    - Git 


resumes: true
resume-list:
    example:
        title: Click here to download


# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
